[package]
name = "script-utils"
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
edition = "2018"

[[bin]]
name = "clean_names"
path = "scripts/clean_names.rs"

[lib]
name = "script_utils"
path = "src/lib.rs"

[dependencies]
anyhow = "^1"
better-panic = "^0.2"
chrono = "^0.4"
shellexpand = "^2"
subprocess = "^0.2"
structopt = "^0.3"
strum = "^0.21"
strum_macros = "^0.21"
